apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: daknodered2-app
  labels:
    app: daknodered2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daknodered2
    spec:
      containers:
      - name: daknodered2
        image: "davekrier/davenodered:v1"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 1880
---
apiVersion: v1
kind: Service
metadata:
  name: daknodered2-app
  labels:
    app: daknodered2
spec:
  type: NodePort
  ports:
  - port: 1880
    targetPort: 1880
    protocol: TCP
    name: daknodered2-port
  selector:
    app: daknodered2
